src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
	const HEAT = [0 => 'Electrique', 1 => 'Gaz'];
	
	public function __construct()
             {
                 $this-> created_at = new \DateTime();
                 $this->options = new ArrayCollection();
             }
	
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
	
	/**
	 * @var string|null
	 * @ORM\Column(type="string", length=255)
	 */
    private $filename;
	/**
	 * NOTE: This is not a mapped field of entity metadata, just a simple property.
	 * @Assert\Image(
	 *     mimeTypes="image/jpeg"
	 * )
	 * @var File|null
	 * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
	 */
	private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min = 10, max = 400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedromms;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $floor;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
    
	
	public function getId(): ?int
                                  {
                                      return $this->id;
                                  }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    
    public function getSlug(): string{
	    return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(?int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedromms(): ?int
    {
        return $this->bedromms;
    }

    public function setBedromms(int $bedromms): self
    {
        $this->bedromms = $bedromms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(?int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }
	
	public function getFormattedPrice(): string
                              	{
                              		return number_format($this->price, 0, '', ' ');
                              	}

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(?int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType():string
     {
    	return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }
	
	/**
	 * @return null|string
	 */
	public function getFilename(): ?string
         	{
         		return $this->filename;
         	}
	
	/**
	 * @param null|string $filename
	 *
	 * @return Property
	 */
	public function setFilename(?string $filename): Property
         	{
         		$this->filename = $filename;
         		return $this;
         	}
	
	/**
	 * @return null|File
	 */
	public function getImageFile(): ?File
         	{
         		return $this->imageFile;
         	}
	
	/**
	 * @param null|File $imageFile
	 *
	 * @return Property
	 */
	public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
    
 
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedromms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, ['choices' => $this->getChoices()])
	        ->add('options', EntityType::class, [
	        	'class' => Option::class,
	            'required' => false,
	            'choice_label' => 'name',
	            'multiple' => true
	        ])
            ->add('imageFile', FileType::class, [
            	'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
    
    public function getChoices(){
    	$choices = Property::HEAT;
    	$outPut = [];
    	foreach ($choices as $k =>$v){
    		$outPut[$v] = $k;
	    }
	    return $outPut;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;

use App\Repository\PropertyRepository;

use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;


class PropertyController extends AbstractController
{
	/**
	* @var PropertyRepository
	*/
	private $repository;
	
	/**
	 * @var ObjectManager
	 */
//	private $em;
	
	public function __construct(PropertyRepository $repository
	/*, ObjectManager $em */)
	{
		$this->repository = $repository;
//		$this->em = $em;
	}
	
	
	/**
	 * @Route("/biens", name="property.index")
	 * @param PaginatorInterface $paginator
	 * @param Request            $request
	 *
	 * @return Response
	 */
//    public function index(PropertyRepository $repository): Response
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
	    /* Insert in database
    	$property = new Property();
        $property->setTitle("Mon premier bien")
		    ->setDescription("Une petite desciption")
		    ->setSurface(225)
		    ->setRooms(4)
		    ->setBedromms(3)
		    ->setSurface(2)
		    ->setPrice(350000)
		    ->setHeat(1)
		    ->setCity("Oued Ellil")
		    ->setAddress("2 Avenue Farhat Hached")
		    ->setPostalCode("2021")
		    ->setSold(3);
	    
	    $em = $this->getDoctrine()->getManager();
	    $em->persist($property);
	    $em->flush();
	    */
	    // Créer une entité qui va représenter notre recherche
	    // Créer un formulaire
	    // Gérer le traitement dans le controller
	    
	    $search = new PropertySearch();
	    $form = $this->createForm(PropertySearchType::class, $search);
	    $form->handleRequest($request);
	    
	    $properties = $paginator->paginate(
	    	$this->repository->findAllVisibleQuery($search),
		    $request->query->getInt('page', 1),
		    12
	    );
	    
	    
	    return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }
	
	/**
	 * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
	 * @param Property            $property
	 * @param string              $slug
	 * @param Request             $request
	 * @param ContactNotification $notification
	 *
	 * @return Response
	 */
	public function show(Property $property, string $slug, Request $request, ContactNotification $notification):
	Response
	{
		if($property->getSlug() !== $slug){
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug(),
			], 301);
		}
		
		$contact = new Contact();
		$contact->setProperty($property);
		$form = $this->createForm(ContactType::class, $contact);
		$form->handleRequest($request);
		if($form->isSubmitted() && $form->isValid()){
			//Send mail
			$notification->notify($contact);
			
			$this->addFlash('success', 'Votre email a bien été envoyé !');
			
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug(),
			]);
		}
		
		return $this->render('property/show.html.twig', [
			'current_menu' => 'properties',
			'property' => $property,
			'form' => $form->createView()
		]);
		
	}
}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
    {% else %}
        <img src="{{ '/images/properties/empty.png' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title"></h5>
        <a href="{{ path('property.show', {'slug': property.slug, 'id': property.id}) }}">
            {{ property.title }}
        </a>
        <p class="card-text">{{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold">
            {{ property.formattedPrice }} €
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Tous nos biens' %}

{% block body %}
    <div class="container mt-4">
        <h1>voir tous nos biens</h1>
        <div class="jumbotron">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
        <div class="row">
        {% for property in properties %}

                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>

        {% endfor %}
        </div>
        <div class="paginati">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}

    <div class="jumbotron">
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            <div class="row">
                <div class="col-md-8">
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto">
                    {% else %}
                        <img src="{{ '/images/properties/empty.png' | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{  property.formattedPrice }} €</div>
                    <a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contacter l'agence</a>
                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}

                        {% if not form.vars.valid %}
                            <div class="alert alert-danger">
                                Erreur de saisie
                            </div>
                        {% endif %}
                        <div class="form-group">
                            <button class="btn btn-primary">Envoyer</button>
                        </div>
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container mt-4">
        <p>{{ property.description | nl2br }}</p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms}} m²</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedromms}} m²</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor}} m²</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }} m²</td>
                    </tr>
                </table>

            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-item">{{  option.name }}</li>
                    {% endfor %}
                </ul>


            </div>
        </div>

    </div>

{% endblock %}